# -*- coding: utf-8 -*-
"""cotacoes_de_acoes_com_grafico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zw1Nmt39uCEqjctpXp2Ity-QN7dfn1CW
"""

import numpy as np
import pandas as pd
import pandas_datareader.data as pd_dr
import matplotlib.pyplot as plt

# Comando para instalação da biblioteca Yahoo Finance.
# pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
yf.pdr_override()

# Definindo parâmetros.
v_ativo = 'PETR4.SA' # Outros: PETR4.SA, BTC-USD, ETH-USD
v_dt_inicio = '2022-01-01'
v_dt_fim = '2022-12-31'

# Obtendo cotações.
cotacoes = pd_dr.get_data_yahoo(v_ativo, start = v_dt_inicio, end = v_dt_fim)

# Gerando o gráfico.
cotacoes['Close'].plot(figsize = (16, 8))
plt.title(v_ativo)

# Exportando para um arquivo do excel.
cotacoes.to_excel("cotacoes.xlsx", index=False)

